### ISSUE TITLE
0.8.1 crashes with “OSError: libtiledb.so: cannot open shared object file: No such file or directory”

### ISSUE THREAD

**Issue by flying-sheep** [TileDB-Inc/TileDB-Py#471]
This happens on travis:

```py
import tiledb
```

```pytb
python/3.8.6/site-packages/tiledb/__init__.py:38: in <module>
    ctypes.CDLL(lib_name)
python/3.8.6/lib/python3.8/ctypes/__init__.py:373: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: libtiledb.so: cannot open shared object file: No such file or directory
```

/edit: yup, 0.8.1 specific. If I specify `tiledb!=0.8.1` it installs 0.8 and my tests run

**Comment by ihnorton** [comment]
Hi @flying-sheep, I've tried to reproduce this on Python 3.8 and Amazon Linux 2 (~CentOS7) using both the conda and pypi packages, and `import tiledb` seems to be fine.

- how did you install
  - if using conda, can you please post output of `conda list tiledb` and `conda list tiledb-py`
- which travis image are you using, if there is such an option?

Thanks

**Comment by flying-sheep** [comment]
travis config should be equivalent to this.

we’re using python 3.8.6 since travis for some reason uses some super old python `3.8` version by default.

```yaml
dist: xenial
language: python
python:
- '3.8.6'
install:
- pip install tiledb==0.8.1
script:
- python -c 'import tiledb'
```

**Comment by eddelbuettel** [comment]
With 

> dist: xenial

you are indicating to Travis here that you prefer 16.04 so you get served "corresponding" versions from that era by default.  

Maybe switching to "bionic" or "focal" can help you?

**Comment by ihnorton** [comment]
(@eddelbuettel in any case, 0.8 was working so this looks like a regression -- I will track it down)

**Comment by flying-sheep** [comment]
might well be! we just didn’t specify a distribution, the old xenial seems to be the default.

**Comment by eddelbuettel** [comment]
Philipp:  Yep.  I tend to roll it forward to more recent distro my CI runs at either backend I generally prefer newer releases.  It's nice to have a choice to test with older release but (to me) I find it gets more in the way.  

Isaiah:  Indeed. Many degrees of freedom with different binary / source / hybrid installation modes.

**Comment by flying-sheep** [comment]
Well, I privately use Arch, so I know all about the pleasures of an up-to-date system :smile: 

I reproduced this using `docker run -it ubuntu:xenial` and then inside:

```bash
apt update
apt upgrade
apt install wget bzip2 python3-pip
wget https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.8.6.tar.bz2
tar xjf python-3.8.6.tar.bz2 --directory /
/opt/python/3.8.6/bin/pip3 install tiledb
/opt/python/3.8.6/bin/python3 -c 'import tiledb'
```

**Comment by flying-sheep** [comment]
But more importantly: It’s still happening in focal. (Didn’t reproduce manually, but the Travis build still fails with `dist: focal`)

**Comment by ihnorton** [comment]
@flying-sheep when I try your [test case](https://github.com/TileDB-Inc/TileDB-Py/issues/471#issuecomment-771918323) in docker, initially I get this:
```
:/# /opt/python/3.8.6/bin/python3 -c 'import tiledb'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/3.8.6/lib/python3.8/site-packages/tiledb/__init__.py", line 3, in <module>
    import ctypes
  File "/opt/python/3.8.6/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

After I run `apt install libffi6`, then the `python3 -c 'import tiledb'` test line succeeds for all of `{0.7.7, 0.8.0, 0.8.1}` TileDB-Py versions.

**Comment by ihnorton** [comment]
Ok I suspect this may be same as [this issue](https://github.com/TileDB-Inc/TileDB-Cloud-Py/pull/120#issuecomment-771533929). Please let me know if it is fixed in TileDB-Py 0.8.2

**Comment by flying-sheep** [comment]
Yes it is!

**Comment by ihnorton** [comment]
Thanks for confirming. The issue was that some build system changes caused the wheels for 0.8.1 to be built against the latest numpy, whereas we need to build against the oldest supported version in order to maintain ABI compatibility (build with old + run with new works fine; build with new, run with old does not). Fixed here: https://github.com/TileDB-Inc/TileDB-Py/pull/472/commits/7a437f89a10aac0734546c06cab35f4cd699c7e8

**Comment by flying-sheep** [comment]
perfect, thank you also for explaining, this way people from the future (hi! is Covid over yet?) can figure this out if necessary

**Comment by zhaolin64** [comment]
After paying a terrible price, it's still not over and continues to spread, but nobody's paying attention to it anymore. @flying-sheep
